### PR TITLE
Add url connection and read timeouts

### PR DESCRIPTION
**Pull request by pavlogs**
Resolution for Issue #8

### CODE REVIEW

**Comment by asolntsev** [comment]
@pavlogs Don't we want to make this timeout configurable? Maybe 10 seconds is not enough in some projects?..

**Review by asolntsev — APPROVED** [review]

**Comment by pavlogs** [comment]
> @pavlogs Don't we want to make this timeout configurable? Maybe 10 seconds is not enough in some projects?..

@asolntsev Good point. IMHO a separate configuration class should be introduced to have greater flexibility and handle such cases.
I can open feature request for later. WDYT?

**Comment by asolntsev** [comment]
Maybe just add another parameter to the related methods?

Any experience with configuration class shows that such a class can quickly grow into an uncontrollable monster with tons of settings. I am a bit afraid of it.

**Comment by pavlogs** [comment]
> grow into an uncontrollable monster

Would agree about this statement  🙂

> Maybe just add another parameter to the related methods?

That method is private so it won't affect publicly available api. As an option and to be consistent with a current approach, another constructor could be introduced (see [example commit](https://github.com/codeborne/pdf-test/compare/main...pavlogs:pdf-test:timeout-configuration)). However it will increase complexity of existing constructors (eg. this [two](https://github.com/codeborne/pdf-test/blob/main/src/main/java/com/codeborne/pdftest/PDF.java#L104-L110)).
Seems like usage of builder suites this class. WDYT? I can open another PR if you think such way of configuration is good enough.

**Comment by asolntsev** [comment]
This private method is used in exactly two public constructors:
* `new PDF(URL url)`, and
* `new PDF(URL url, int startPage, int endPage)`.

I agree, adding 2 more methods would be too much.
Probably yes, the builder is a good idea.

**Comment by asolntsev** [comment]
@pavlogs Yes, we can do a similar change in `xls-test`, why not? 

Sorry, I didn't undestand how making `readBytes` public solves our problem.

**Comment by pavlogs** [comment]
Excuse me for any possible confusion. The general idea was to make timeout configurable. I thought it would be clear from the added [tests](https://github.com/codeborne/pdf-test/compare/main...pavlogs:pdf-test:timeout-config#diff-04c4e6afa4dde9bd1c44a4dea8b4f362c1051e72f59bdb68a406f2429980df64R52-R57) how it could be achieved. From the framework point of view only [readBytes](https://github.com/codeborne/pdf-test/compare/main...pavlogs:pdf-test:timeout-config#diff-5a30a3c26776687e26d56e429578cec318ba5516123a109e972ffd6ca2badb71R125) with `URLConnection` in the signature was added. [Constructor](https://github.com/codeborne/pdf-test/blob/main/src/main/java/com/codeborne/pdftest/PDF.java#L92) with byte[] is available.
So, to make long story short. Adding public method is not mandatory - url connection timeout could be configured without changing anything.

**Pull request merged**
